### ISSUE TITLE
stskeygen@2.2.10 2.2.0: decompress error

### ISSUE THREAD

**Issue by arvindmaurya37** [Cimpress-MCP/stskeygen-installers#1]
While Installing latest stskeygen it throws below  exception
<img width="658" alt="image" src="https://user-images.githubusercontent.com/30270652/201091751-09da9227-07e0-4b33-8811-f81c1b90f814.png">

**Comment by maclennann** [comment]
Hi @ArvindMaurya1996 - as mentioned in chat I'm going to close this issue here and you can follow along with the internally-reported issue.
